[package]
name = "webauthn-rs"
version = "0.3.0-alpha.2"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"
build = "build.rs"

description = "Webauthn Framework for Rust Web Servers"
# documentation = "..."
# homepage = "..."
repository = "https://github.com/kanidm/webauthn-rs"
readme = "README.md"
keywords = ["webauthn", "authentication"]
categories = ["authentication", "web-programming"]
license = "MPL-2.0"

[dependencies]
base64 = "0.13"
log = "0.4"
nom = "4"
serde = "1.0"
serde_bytes = "0.11"
serde_cbor = "0.11"
serde_derive = "1.0"
serde_json = "1.0"
# We could consider replacing this with openssl rand.
openssl = "0.10"
rand = "0.8"
thiserror = "1.0"

[dev-dependencies]
askama = "0.10"
tide = "0.15"
tide-rustls = "0.1"
askama_tide = "0.12"
async-std = { version = "1.6", features = ["attributes"] }

openssl = "0.10"

lru = "0.6"

structopt = { version = "0.3", default-features = false }
rustls = "0.19.0"
env_logger = "0.8.2"

