

[workspace]
resolver = "2"
members = [
    # Support Libraries
    "base64urlsafedata",
    "webauthn-rs-proto",
    "webauthn-rs-core",
    # The actually library.
    "webauthn-rs",
    # Authenticator interactions
    "fido-hid-rs",
    "webauthn-authenticator-rs",
    # caBLE tunnel server
    "cable-tunnel-server/backend",
    "cable-tunnel-server/common",
    "cable-tunnel-server/frontend",
    "fido-key-manager",
    # Authenticator CLI,
    "authenticator-cli",
    # Tutorial / Example sites.
    "tutorial/server/tide",
    "tutorial/server/axum",
    "tutorial/server/actix_web",
    "tutorial/wasm",
    # Attestatation struct format
    "attestation-ca",
    # Fido MDS tools
    "fido-mds",
    "fido-mds-tool",
    # Our Device Catalog
    "device-catalog",
    # "device-catalog-tool",
    # The compat tester
    "compat_tester/webauthn-rs-demo",
    "compat_tester/webauthn-rs-demo-shared",
    # Ssh Key Attestation
    "sshkey-attest",
]

# Due to --cfg=web_sys_unstable_apis
exclude = ["compat_tester/webauthn-rs-demo-wasm"]

[workspace.dependencies]
base64urlsafedata = { path = "./base64urlsafedata", version = "0.1.3" }
cable-tunnel-server-common = { path = "./cable-tunnel-server/common", version = "0.1.0" }
fido-hid-rs = { path = "./fido-hid-rs", version = "0.5.0-dev" }
webauthn-authenticator-rs = { path = "./webauthn-authenticator-rs", version = "0.5.0-dev" }
webauthn-rs = { path = "./webauthn-rs", version = "0.5.0-dev" }
webauthn-rs-core = { path = "./webauthn-rs-core", version = "0.5.0-dev" }
webauthn-rs-proto = { path = "./webauthn-rs-proto", version = "0.5.0-dev" }
webauthn-attestation-ca = { path = "./attestation-ca", version = "0.1.0" }
webauthn-rs-device-catalog = { path = "./device-catalog", version = "0.5.0-20230418" }

async-std = { version = "1.6", features = ["attributes"] }
base64 = "0.21"
clap = { version = "^4.2.4", features = ["derive", "env"] }
compact_jwt = "0.2.3"
futures = "^0.3.25"
hex = "0.4.3"
http = "^0.2.9"
http-body = "=1.0.0-rc.2"
http-body-util = "=0.1.0-rc.2"
hyper = { version = "=1.0.0-rc.3", default-features = false, features = [
    "http1",
] }
nom = "7.1"
peg = "0.8.1"
openssl = "^0.10.56"
rand = "0.8"
serde = { version = "^1.0.141", features = ["derive"] }
serde_cbor_2 = { version = "0.12.0-dev" }
serde_json = "^1.0.79"
tide = "0.16"
thiserror = "^1.0.37"
tokio = { version = "1.22.0", features = [
    "sync",
    "test-util",
    "macros",
    "net",
    "rt-multi-thread",
    "time",
] }
tokio-native-tls = "^0.3.1"
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-tungstenite = { version = "^0.18.0", features = ["native-tls"] }
tracing = "^0.1.35"
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "std",
    "fmt",
] }
tungstenite = { version = "^0.18.0", default-features = false, features = [
    "handshake",
] }
url = "2"
uuid = "^1.1.2"
