[package]
name = "webauthn-rs"
version = "0.3.0-alpha.7"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"
build = "build.rs"

description = "Webauthn Framework for Rust Web Servers"
# documentation = "..."
# homepage = "..."
repository = "https://github.com/kanidm/webauthn-rs"
readme = "README.md"
keywords = ["webauthn", "authentication"]
categories = ["authentication", "web-programming"]
license = "MPL-2.0"

[features]
core = ["openssl", "rand"]
default = ["core"]
wasm = ["wasm-bindgen", "web-sys", "js-sys"]

[dependencies]
serde = "1.0"
nom = "4"
base64 = "0.13"
serde_derive = "1.0"
thiserror = "1.0"
log = "0.4"
serde_bytes = "0.11"
serde_cbor = "0.11"
serde_json = "1.0"
# We could consider replacing this with openssl rand.
openssl = { version = "0.10", optional = true }
rand = { version = "0.8", optional = true }

# Webauthny bits.
wasm-bindgen = { version = "0.2", features = ["serde-serialize"], optional = true }
web-sys = { version = "0.3", features = ["CredentialCreationOptions", "CredentialRequestOptions", "PublicKeyCredential"], optional = true }
js-sys = { version = "0.3", optional = true }

[dev-dependencies]
askama = "0.10"
tide = "0.16"
tide-rustls = "0.2"
askama_tide = "0.13"
async-std = { version = "1.6", features = ["attributes"] }
openssl = "0.10"
lru = "0.6"
structopt = { version = "0.3", default-features = false }
rustls = "0.19.0"
env_logger = "0.8.2"
# Workaround for compilation bug: https://github.com/Geal/nom/issues/1284
funty="=1.1.0"
